### ISSUE TITLE
Input Field to filter tests

### ISSUE THREAD

**Issue by Freshchris01** [connorshea/vscode-ruby-test-adapter#23]
I would really like to have an input field to be able to filter the list of tests.

Will have a look at this soon.

**Comment by connorshea** [comment]
Hey! A few things:

1. This isn't really a problem that can be solved in this adapter, since the adapter just provides data to [the Test Explorer extension](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer). If anything the the Test Explorer UI is what this issue should be opened in.
2. That said, this can't be done by the Test Explorer UI either, because of limitations in the VS Code extension API. Technically, if the entire test tree were replaced by an entirely custom webview, it'd be possible, but since the extension currently uses the TreeView provided by VS Code, it's at the mercy of whatever features the TreeView has.
3. With _that_ said, you'll be happy to know that this feature was actually introduced last week! In VS Code 1.37, the tree view used by extensions was updated to include filtering and some other improvements.

To filter:
- Focus the test tree view (e.g. click on a test)
- Start typing and you should see an orange (this might vary depending on your theme?) box in the top right of the test view.
- Hover over it and there'll be a button to filter and a button to close it. Click filter, obviously.

Hope that helps! :D

<img width="469" alt="Screen Shot 2019-08-13 at 5 21 41 PM" src="https://user-images.githubusercontent.com/2977353/62984032-d41c4780-bdee-11e9-84e3-ae27e4f6e7b5.png">

**Comment by Freshchris01** [comment]
Thanks a lot for the tipps! Will have a look into this when I find some time.

**Comment by Freshchris01** [comment]
Closing, because filtering now exists within the vscode [Tree Widget](https://code.visualstudio.com/updates/v1_31#_new-tree-widget).
